# Generated by Django 4.0.5 on 2022-06-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='allow comments'),
        ),
    ]
