# Generated by Django 4.0.5 on 2022-06-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='E-mail address', max_length=120)),
                ('full_name', models.CharField(help_text='Full name', max_length=255)),
                ('nickname', models.CharField(blank=True, help_text='Nickname', max_length=20, null=True)),
                ('show_nickname', models.BooleanField(default=False)),
            ],
        ),
    ]
