# Generated by Django 4.0.5 on 2022-06-25 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_rename_subscribers_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
    ]
